name: CI
on: [push]
jobs:
  standard-checks:
    name: Lint and test code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Run eslint
        run: npm run lint

      - name: Run jest
        run: npm t